harishbalakrishnan3/aiops_e2e

features/steps/cdo_apis.py, features/steps/correlation.py, features/steps/metrics.py, features/steps/utils.py
Description : 
Removing duplicate code , removing hardcoded url and general code structure improvements
=> Code improvements

features/100_ElephantFlows.feature, features/200_Correlation.feature
Description : 
1)Elephant flow correcting the data structure for app info 
2)Fixing the timing issue due to which one of the insight was intermittently getting missed
3)Feature test improvement
=> Adding Elephant flow fix and general improvement

features/steps/ra_vpn.py
Description:
Fixing the ra vpn scenario
=> ra vpn sceario fix

features/100_ElephantFlows.feature, features/300_RAVPN.feature, features/environment.py, features/steps/cdo_apis.py
Description:
Fixing parallel execution failures
=> Fixing paralelle execution

features/200_Correlation.feature, features/environment.py
Remove insight clear in correlation
=> remove insight clear from correlation

features/000_Onboard.feature, features/steps/onboard.py
Check for partial success state in Onboard test
=> E2E Check for Patial success in onboard

features/steps/ra_vpn.py, features/steps/utils.py
Making noise deterministic as a prerequisite to insight data testing
=> Making noise deterministic

features/100_ElephantFlows.feature
Description :
Elephant flow timeout inctrease
=> increasing elephant flow timeout

.gitignore, features/400_Anomaly.feature, features/model.py, features/steps/anomaly.py, features/steps/common_steps.py, features/steps/metrics.py, features/steps/ra_vpn.py, features/steps/time_series_generator.py, features/steps/utils.py, pyproject.toml, utils/backfill.sh
Description : 
1)Integrating traffic generator library with correlation 
2)Adding anomaly detection backfill 
3)Uncomments ravpn id data already present check to backfill new data and confirm the functionality is intact
=> Integrating traffic generator

poetry.lock, pyproject.toml
Description : 
Lock file update
=> Lock file update

.pre-commit-config.yaml, README.md, features/environment.py, features/model.py, features/steps/cdo_apis.py, features/steps/common_steps.py, features/steps/correlation.py, features/steps/elephant_flow.py, features/steps/env.py, features/steps/metrics.py, features/steps/onboard.py, features/steps/ra_vpn.py, features/steps/time_series_generator.py, features/steps/utils.py, pyproject.toml
Adding code formatter for better readability and easier formatting
=> Adding code formatter 

poetry.lock
=> update lock file

features/400_Anomaly.feature, features/model.py, features/steps/anomaly.py, features/steps/common_steps.py, features/steps/time_series_generator.py, features/steps/utils.py
Description : 
1)Added support for counter metrics 
2)Adding throughput anomaly scenario added 
3)Fixed previously breaking changes
Expected trend pushed for throughput
=> Adding throughput anomaly scenario 

features/400_Anomaly.feature, features/steps/common_steps.py
Adding amplitude as option since different timeseries will need diiferent amplitude configuration . Default will be 20
=> Adding Amplitude as an option for backfill  (optional field)

features/environment.py, features/model.py, features/steps/ra_vpn.py, features/steps/utils.py
Logging improvements
1. Print device selected summary in `after_all()` hook
2. Print "Time to complete backfill" in RAVPN Scenario
3. Print number of devices for which RA VPN in enabled and their names
4. Print number of total available devices
=> Minor logging improvements

features/400_Anomaly.feature, features/steps/common_steps.py, features/steps/ra_vpn.py
Addinf trigger forecast for anomaly detection using common step
=> Adding trigger forecast for anomaly detection 

features/400_Anomaly.feature
Reducing backfill duration from 4 weeks to 2 weeks for Anomaly Feature
=> Reducing backfill duration from 4 weeks to 2 weeks for Anomaly Feature

features/steps/common_steps.py
Fixing subscriber names for anomaly detection
=> Fixing subscriber names for anomaly detection

features/steps/time_series_generator.py, features/steps/utils.py
Fixing time series generation issue in live fill common step and other minor fixes
=> Correcting transition start time 

features/400_Anomaly.feature, features/steps/common_steps.py, features/steps/env.py
Adding trigger method through API temporarily till the anomaly app becomes stable
=> Adding trigger method for anomaly scenario

features/steps/cdo_apis.py
Impacted resource field assertions fix
=> impacted resource fix

features/200_Correlation.feature, features/environment.py, features/steps/cdo_apis.py, features/steps/onboard.py, features/steps/utils.py
Remove input packet size as it does not match as interface metrics are not present in HA case
=> Aiops e2e/correlation metric match fix

features/400_Anomaly.feature, features/steps/common_steps.py, features/steps/utils.py
This PR enables sanity E2Es for Connections and Network Anomaly.
=> Anomaly Detection Sanity E2Es

Jenkinsfile
Marking error files for easier data processing
=> Error File Marking 

analysis/agents/datadog_agent/agent.py, analysis/agents/jenkins_agent/agent.py, analysis/agents/jenkins_agent/log_parser.py, analysis/agents/jenkins_agent/tools.py, analysis/analyzer.py, analysis/main.py, features/steps/cdo_apis.py, features/steps/ra_vpn.py, features/steps/utils.py
1) Log level fix 
2) Ran Linter
=> Log Level Fix 

analysis/data_proccesor/data_processor.py
Adding Data Processor Pipeline
File will be structure as below : 
```
--analysis
----raw (contains raw files copied from jenkins logs)
----processed (each feature will have a folder with each scenario having a file)
--archive (archive is temporary , this will be the jenkins logs directory on server)
```
=> Data processor Pipeline 

.gitignore, analysis/agents/datadog_agent/tools.py, analysis/agents/jenkins_agent/agent.py, analysis/agents/jenkins_agent/tools.py, analysis/analyzer.py, analysis/data_proccesor/data_processor.py, analysis/model.py, analysis/utils/utils.py
1) Adding task creator node - which extracts scenario data , tenant data and picks up log file 
2) Adding subgraph that actually does the analysis per task 
3) Result consolidator 
-  Need work to pick up data from each  parallel task and consolidate it 
AnalyzerGraph - the sugbraph that will be executed for each scenario / scenario log ( this includes the jenkins analyzer and data dog analyzer 
Task Creator and Result Consolidator is the parent graph that invokes tasks for each issue and consolidates them 
Analyzer graph Expansion:
=> Parallel Task excution and creation 
